{% set name = "colorpedia" %}
{% set version = "1.2.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/colorpedia-{{ version }}.tar.gz
  sha256: 34d17766abeddf495faecc3a65f1e74dad0d7a8fd0771f55c3bceb4092df4205

build:
  number: 0
  noarch: python
  entry_points:
    - color = colorpedia.cli:entry_point_color
    - colorpedia = colorpedia.cli:entry_point_colorpedia
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools >=42
    - setuptools_scm >=3.4
  run:
    - python >=3.6
    - dataclasses >=0.6
    - fire >=0.3.1

test:
  imports:
    - colorpedia
  commands:
    - color --help
    - colorpedia --help
  requires:
    - pip

about:
  home: https://github.com/joowani/colorpedia
  summary: Command-line tool for looking up colors
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - joowani
