{% set name = "colorpedia" %}
{% set version = "1.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/colorpedia-{{ version }}.tar.gz
  sha256: a54e1f509cd028b473b7fae029f2b7bb29c3b0d666ea05a6262c2ba335ad29ac

build:
  number: 0
  noarch: python
  entry_points:
    - color = colorpedia.cli:entry_point_color
    - colorpedia = colorpedia.cli:entry_point_colorpedia
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools >=42
    - setuptools_scm >=3.4
  run:
    - python >=3.6
    - dataclasses >=0.6
    - fire >=0.3.1

test:
  imports:
    - colorpedia
  commands:
    - color --help
    - colorpedia --help
  requires:
    - pip

about:
  home: https://github.com/joowani/colorpedia
  summary: Command-line tool for looking up colors
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - joowani
